version: '3.3'

services:
  app:
    container_name: php_app
    image: giovanegurgel/proj_php_app:latest
    restart: always
    working_dir: /var/www/public/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../src:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_app
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
