version: '3.3'

services:
  app:
    container_name: appteste
    image: giovanegurgel/appbase:latest
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../src:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
  nginx:
    image: giovanegurgel/nginx:latest
    container_name: nginx_app
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
